# Generated by Django 2.1 on 2018-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiveSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites_name', models.CharField(max_length=200)),
                ('sites_addr', models.CharField(max_length=400)),
                ('sites_avg_price', models.IntegerField(default=0)),
                ('sites_call_phone', models.CharField(max_length=20)),
                ('sites_numbers', models.IntegerField(default=0)),
                ('sites_run_time', models.CharField(max_length=200)),
            ],
        ),
    ]
