# Generated by Django 2.1 on 2018-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivesites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivesite',
            name='sites_price',
            field=models.CharField(default='0', max_length=400),
            preserve_default=False,
        ),
    ]
