# Generated by Django 2.0.7 on 2018-07-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soccer_site_name', models.CharField(max_length=200)),
                ('soccer_site_addr', models.CharField(max_length=500)),
                ('soccer_site_linkman', models.CharField(max_length=100)),
                ('soccer_site_mobile', models.CharField(max_length=100)),
                ('soccer_site_star_level', models.IntegerField(max_length=2)),
                ('soccer_site_start', models.CharField(max_length=1)),
            ],
        ),
    ]
