# Generated by Django 2.0.7 on 2018-07-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqltest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccersite',
            name='soccer_site_avg_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soccersite',
            name='soccer_site_star_level',
            field=models.IntegerField(default=0),
        ),
    ]
