# Generated by Django 2.0.7 on 2018-07-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqltest', '0002_auto_20180710_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soccersite',
            name='soccer_site_start',
        ),
    ]
